# Generated by Django 4.2.4 on 2023-08-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mushroomimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='general_information',
        ),
        migrations.RemoveField(
            model_name='species',
            name='medicinal_properties',
        ),
        migrations.RemoveField(
            model_name='species',
            name='morphological_characteristics',
        ),
        migrations.RemoveField(
            model_name='species',
            name='species_information',
        ),
        migrations.AddField(
            model_name='species',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
