# Generated by Django 4.2.4 on 2023-08-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_species_general_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='general_information',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='medicinal_properties',
            field=models.ManyToManyField(null=True, to='api.medicinalproperty'),
        ),
        migrations.AddField(
            model_name='species',
            name='morphological_characteristics',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='species_information',
            field=models.TextField(null=True),
        ),
    ]
